"""Curated colloquial-language seed knowledge for Bob.

These are product-owned seed documents, not user-learned memories. Each table
packs 10 everyday spoken phrasings into one knowledge document so Bob learns a
wide surface area without turning the knowledge DB into hundreds of loose rows.
"""


_COLLOQUIAL_TABLES = [
    {
        "title": "email moi va inbox",
        "intent": "email.latest_summary / email.inbox_triage",
        "meaning": "Nguoi dung muon Bob xem email moi, email gan day, hoac inbox dang can chu y.",
        "behavior": "Neu Gmail chua ket noi thi noi ro. Neu da ket noi thi lay email that, khong bia nguoi gui/noi dung.",
        "tags": "email,gmail,inbox,khau ngu",
        "phrases": [
            "coi giup tui may mail moi",
            "bob xem hom nay hop thu co gi hot khong",
            "co thu nao vua vo khong",
            "doc nhanh inbox dum minh",
            "mail moi nhat co gi vay",
            "kiem tra hop thu cai coi",
            "co ai gui gi quan trong khong",
            "xem gium toi may email gan day",
            "inbox dang co gi can xu ly",
            "mail nao moi nhan thi tom tom cho toi",
        ],
    },
    {
        "title": "tim email theo cach noi doi thuong",
        "intent": "email.search",
        "meaning": "Nguoi dung muon tim email theo nguoi gui, chu de, tu khoa, moc thoi gian.",
        "behavior": "Dung Gmail search/query that. Neu sender khong phai email address thi coi la keyword hoac ten nguoi.",
        "tags": "email,search,tim mail,khau ngu",
        "phrases": [
            "kiem mail cua anh Nam giup toi",
            "tim lai cai mail ve hop dong hom bua",
            "co thu nao cua cong ty kia khong",
            "luc truoc ai gui file bao gia nhi",
            "moi tim email noi ve deadline",
            "loc giup mail co chu invoice",
            "co email nao tu truong gui tuan nay khong",
            "tim thu cua chi Lan hoi ve meeting",
            "kiem trong inbox co cai nao lien quan den do an",
            "mail nao co dinh kem file pdf vay",
        ],
    },
    {
        "title": "email chua doc va can phan hoi",
        "intent": "email.inbox_triage",
        "meaning": "Nguoi dung hoi email chua doc, email quan trong, email can tra loi.",
        "behavior": "Phan loai inbox bang du lieu that, uu tien unread, yeu cau xac nhan, deadline, cau hoi can tra loi.",
        "tags": "email,unread,triage,reply,khau ngu",
        "phrases": [
            "mail nao chua doc vay bob",
            "co cai nao can rep gap khong",
            "loc cho toi may thu can tra loi",
            "inbox co gi can xu ly lien khong",
            "mail nao quan trong nhat bay gio",
            "co ai dang doi minh tra loi khong",
            "gom may email can follow up",
            "doc va xep muc do uu tien email giup toi",
            "co thu nao deadline khong",
            "mail nao bo qua duoc mail nao can xem",
        ],
    },
    {
        "title": "danh dau email da doc chua doc",
        "intent": "email.mark_read / email.mark_unread",
        "meaning": "Nguoi dung muon doi trang thai email read/unread bang cach noi tat.",
        "behavior": "Danh dau email phu hop neu tim duoc. Neu mo ho, hoi ro email nao hoac dung ket qua vua nhac gan nhat.",
        "tags": "email,mark read,mark unread,khau ngu",
        "phrases": [
            "danh dau may mail do la da doc",
            "cho cai thu cua sep thanh unread",
            "mail nay doc roi nha",
            "de lai chua doc giup toi",
            "tick da xem cai email vua noi",
            "bo trang thai chua doc cua mail nay",
            "mark read cai thu cua phong nhan su",
            "mark unread cai mail hop dong",
            "danh dau het may mail tim duoc la da doc",
            "cai nay de chut nua doc tiep",
        ],
    },
    {
        "title": "soan tra loi email bang loi noi",
        "intent": "email.summary_reply",
        "meaning": "Nguoi dung muon Bob soan nhap tra loi email hoac goi y noi dung phan hoi.",
        "behavior": "Chi soan nhap, khong tu gui. Neu gui that thi can xac nhan ro tu user.",
        "tags": "email,reply,draft,khau ngu",
        "phrases": [
            "rep giup toi lich su hon xiu",
            "soan cau tra loi cho mail nay",
            "viet gium minh mail bao la minh dong y",
            "tra loi ho la minh se xem lai",
            "giup toi noi kheo la chua kip lam",
            "draft cho toi cai mail cam on",
            "viet phan hoi ngan gon thoi",
            "soan mail xin doi lich hen",
            "noi voi ho la toi nhan duoc roi",
            "viet giup cai mail tu choi nhe nhang",
        ],
    },
    {
        "title": "tao lich hen bang khau ngu",
        "intent": "schedule.create",
        "meaning": "Nguoi dung muon tao lich, nhac viec, hen gap, goi dien, deadline co thoi gian.",
        "behavior": "Trich title/time/location/attendees neu co. Luon hoi xac nhan truoc khi tao lich that.",
        "tags": "lich,schedule,create,hen,khau ngu",
        "phrases": [
            "lat nua 3h nho tui hop nhe",
            "dat giup cai hen voi khach chieu mai",
            "mai 9h keu minh nop bai",
            "toi nay nhac di mua do",
            "thu sau set lich gap team",
            "book cho toi cuoc call voi anh Minh",
            "nho tui 2 tieng nua goi lai",
            "tao lich phong van sang thu hai",
            "cho vao lich cai deadline nop report",
            "hen bac si rang luc 5h chieu mai",
        ],
    },
    {
        "title": "doi lich va reschedule bang loi noi",
        "intent": "schedule.update",
        "meaning": "Nguoi dung muon doi gio, doi ngay, doi noi dung, doi dia diem mot lich da co.",
        "behavior": "Tim lich sap toi khop tu khoa, hien lai lich tim duoc, hoi xac nhan truoc khi sua.",
        "tags": "lich,schedule,update,reschedule,khau ngu",
        "phrases": [
            "doi cai lich hop sep sang 5h",
            "chuyen hen khach qua ngay mai",
            "dời buoi call tu 3h sang 4h",
            "lich phong van doi qua thu ba",
            "sua gio gap team thanh chieu nay",
            "doi dia diem hop sang quan cafe",
            "cap nhat cai lich nop bai thanh toi mai",
            "reschedule meeting voi John",
            "cai hen bac si doi qua tuan sau",
            "keo lich gym qua 7h toi",
        ],
    },
    {
        "title": "huy va xoa lich bang loi noi",
        "intent": "schedule.delete",
        "meaning": "Nguoi dung muon huy/xoa/bo mot lich hen da co.",
        "behavior": "Tim lich khop va hoi xac nhan truoc khi xoa/huy. Neu nhieu lich khop thi hoi chon.",
        "tags": "lich,schedule,delete,cancel,khau ngu",
        "phrases": [
            "huy giup cai lich hop chieu nay",
            "xoa hen voi khach ngay mai",
            "bo cai nhac di gym toi nay",
            "cancel meeting voi team",
            "lich phong van khong can nua",
            "xoa deadline nop report di",
            "huy buoi call voi John",
            "bo khoi lich cai hen bac si",
            "khong di nua xoa lich do giup",
            "dẹp cai lich 3h chieu nay",
        ],
    },
    {
        "title": "hoi lich co gi bang khau ngu",
        "intent": "schedule.list",
        "meaning": "Nguoi dung muon xem lich hom nay, tuan nay, tuan sau, hoac mot khoang thoi gian.",
        "behavior": "Doc lich FlowMate/Calendar that theo window. Khong bia them su kien.",
        "tags": "lich,schedule,list,calendar,khau ngu",
        "phrases": [
            "nay minh co hen gi khong",
            "hom nay lich sao bob",
            "tuan sau co gi trong calendar",
            "co meeting nao sap toi khong",
            "mai toi ban khong",
            "xem lich chieu nay giup tui",
            "lich tuan nay day khong",
            "co cai hen nao trung nhau khong",
            "doc lich ngay mai cho toi",
            "toi nay co viec gi tren lich khong",
        ],
    },
    {
        "title": "xep lich ngay va goi y khung gio",
        "intent": "schedule.suggest_plan",
        "meaning": "Nguoi dung co danh sach viec va muon Bob sap xep vao khung gio hop ly.",
        "behavior": "Goi engine goi y lich, tranh trung lich san co. Chi de xuat, khong tao lich that neu chua xac nhan.",
        "tags": "lich,goi y,xep lich,plan day,khau ngu",
        "phrases": [
            "xep giup ngay hom nay voi yoga nau an hoc bai",
            "sap lich cho tui may viec nay",
            "chia thoi gian giup minh lam bai tap va don nha",
            "hom nay co nhieu viec qua bob xep lich dum",
            "goi y khung gio cho gym va lam report",
            "toi nen lam viec nao truoc trong ngay",
            "plan my day voi may task nay",
            "arrange lich hom nay cho hop ly",
            "co the xep tui lich hoc voi lam viec khong",
            "chia slot cho cac hoat dong nay",
        ],
    },
    {
        "title": "dua viec vao checklist bang loi noi",
        "intent": "checklist.create",
        "meaning": "Nguoi dung muon them nhieu viec vao checklist/to-do, khong can gio cu the.",
        "behavior": "Tach tung viec, gan priority neu co tu gap/khong gap, them checklist ngay vi de hoan tac.",
        "tags": "checklist,todo,task,khau ngu",
        "phrases": [
            "cho may viec nay vao checklist",
            "hom nay tui can rua chen hoc bai di cho",
            "them dum lam slide va gui file",
            "ghi lai viec mua sua don phong",
            "list giup tui cac viec can lam",
            "dua may hoat dong nay vao to do",
            "tao checklist voi gym nau com doc sach",
            "nho may viec nay cho tui nha",
            "cho vao danh sach hom nay",
            "them nhanh may task nay",
        ],
    },
    {
        "title": "uu tien deadline va muc do gap",
        "intent": "checklist.create / overview.daily_brief",
        "meaning": "Nguoi dung noi ve viec gap, quan trong, khong gap, ranh thi lam.",
        "behavior": "Gan priority tung viec rieng, khong ap dung mot muc do cho toan bo neu tung item co tu rieng.",
        "tags": "priority,deadline,urgent,checklist,khau ngu",
        "phrases": [
            "cai nay gap nha bob",
            "viec nay quan trong lam",
            "rảnh thi lam cai don nha",
            "khong gap dau de sau cung duoc",
            "deadline truoc 5h chieu nay",
            "uu tien cai report truoc",
            "cai nay phai xong trong hom nay",
            "viec kia de mai cung duoc",
            "sap xep tu cai can gap nhat",
            "danh dau cai nop bai la high priority",
        ],
    },
    {
        "title": "hoc tap bai tap va deadline sinh vien",
        "intent": "student workflow",
        "meaning": "Nguoi dung noi theo kieu hoc sinh/sinh vien ve mon hoc, bai tap, deadline, thi cu.",
        "behavior": "Uu tien deadline hoc tap, co the tao checklist, goi y lich hoc, hoac tao nhac nho neu co moc gio.",
        "tags": "student,study,homework,deadline,khau ngu",
        "phrases": [
            "toi con bai tap toan chua lam",
            "mai nop do an roi bob oi",
            "nhac tui hoc anh van toi nay",
            "xep lich on thi giup toi",
            "cho mon ly vao checklist",
            "co deadline mon marketing tuan nay",
            "chia lich hoc cho bai kiem tra",
            "toi phai lam slide thuyet trinh",
            "sap lich hoc bai voi lam project nhom",
            "nhac di hoc luc 7h sang mai",
        ],
    },
    {
        "title": "workflow cong viec va follow up",
        "intent": "worker workflow",
        "meaning": "Nguoi dung noi ve viec van phong, khach hang, sep, bao cao, follow up.",
        "behavior": "Gom thanh task/checklist, goi y lich neu co thoi gian, hoac tim/soan email neu co mail.",
        "tags": "work,workflow,follow up,khau ngu",
        "phrases": [
            "nhac follow up khach hang",
            "hom nay phai gui bao cao cho sep",
            "them viec check hop dong vao checklist",
            "toi can goi nha cung cap luc 4h",
            "xep giup viec meeting va lam report",
            "co mail khach nao can tra loi khong",
            "doi lich hop noi bo sang chieu",
            "soan mail update tien do",
            "tim lai file bao gia khach gui",
            "gom viec trong ngay thanh uu tien",
        ],
    },
    {
        "title": "tong hop ngay bang cach noi ngan",
        "intent": "overview.daily_brief",
        "meaning": "Nguoi dung muon Bob gom email, lich, checklist, viec can lam trong ngay.",
        "behavior": "Dung Overview/email/calendar/history that, noi ro nguon nao co/chua co.",
        "tags": "overview,daily brief,tong hop,khau ngu",
        "phrases": [
            "hom nay toi co gi",
            "tom ngay nay cho tui",
            "bay gio can lam gi truoc",
            "co gi dang doi minh khong",
            "cho toi buc tranh tong quan",
            "ngay nay co deadline mail lich nao",
            "bob xem giup hom nay ban khong",
            "uu tien trong ngay la gi",
            "co viec nao sot khong",
            "brief nhanh ngay hom nay",
        ],
    },
    {
        "title": "hoi lich su hoat dong bang khau ngu",
        "intent": "history.list",
        "meaning": "Nguoi dung muon xem lai viec da lam, chat truoc do, email/lich da xu ly.",
        "behavior": "Doc History that. Phan biet voi danh sach viec sap lam.",
        "tags": "history,activity,da lam,khau ngu",
        "phrases": [
            "nay toi lam gi roi bob",
            "hom qua minh co xu ly gi",
            "luc nay minh vua nho bob lam gi",
            "xem lai lich su chut",
            "toi da tao lich nao roi",
            "hoi nay bob noi gi nhi",
            "co ghi lai viec da lam khong",
            "nhac lai may thao tac gan day",
            "today what did i do",
            "cho coi activity vua roi",
        ],
    },
    {
        "title": "doi che do lam viec bang loi noi",
        "intent": "settings.update_mode",
        "meaning": "Nguoi dung muon doi user mode sang student/worker/freelancer/creator/business/mentor/teacher.",
        "behavior": "Doi mode neu nhan dien ro. Neu mo ho thi hoi lai. Day la thao tac it rui ro va co the lam ngay theo current policy.",
        "tags": "settings,mode,user mode,khau ngu",
        "phrases": [
            "tu nay toi di hoc nha",
            "doi qua che do sinh vien",
            "minh lam freelance roi",
            "chuyen bob sang mode giao vien",
            "toi dang lam content creator",
            "doi thanh che do kinh doanh",
            "set mode worker giup toi",
            "toi lam mentor cho team",
            "khong phai sinh vien nua toi di lam roi",
            "dung phong cach van phong nha",
        ],
    },
    {
        "title": "gio hien tai va ngay thang",
        "intent": "time.current",
        "meaning": "Nguoi dung hoi gio/ngay hien tai bang cach noi ngan hoac thieu dau.",
        "behavior": "Dung dong ho backend theo Asia/Ho_Chi_Minh/UTC+7. Khong goi AI va khong dung knowledge cu.",
        "tags": "time,current time,ngay gio,khau ngu",
        "phrases": [
            "may gio roi bob",
            "gio viet nam la may gio",
            "hom nay ngay may",
            "bay gio la luc nao",
            "coi dum gio hien tai",
            "today date la gi",
            "what time is it in vietnam",
            "gio vn bay gio",
            "nay la thu may",
            "bob coi dong ho giup toi",
        ],
    },
    {
        "title": "tra cuu internet bang loi noi",
        "intent": "internet.research",
        "meaning": "Nguoi dung muon Bob tim tren web hoac can thong tin moi/cap nhat.",
        "behavior": "Research web cong khai, trich nguon URL. Chi luu lesson neu la learning query da curate.",
        "tags": "internet,web,research,khau ngu",
        "phrases": [
            "len mang coi giup tui",
            "tim tren google cai nay",
            "research nhanh ve chu de nay",
            "co tin moi ve cai do khong",
            "kiem nguon tren internet",
            "search web dum toi",
            "cap nhat moi nhat la sao",
            "doc may nguon public ve no",
            "tim link tham khao giup",
            "hien nay nguoi ta lam cach nao",
        ],
    },
    {
        "title": "xac nhan huy bo va dong y",
        "intent": "confirmation flow",
        "meaning": "Nguoi dung phan hoi cac card/goi y cua Bob bang dong y, huy, sua lai.",
        "behavior": "Neu action can confirm thi chi lam khi co xac nhan ro; neu user huy thi khong thuc hien.",
        "tags": "confirm,cancel,apply,khau ngu",
        "phrases": [
            "ok lam di",
            "chot nha bob",
            "dung roi tao di",
            "thoi khoi",
            "huy cai do",
            "chua dung de toi sua lai",
            "ap dung giup toi",
            "khong phai cai nay",
            "de sau di",
            "yes confirm",
        ],
    },
    {
        "title": "sua loi va doi y giua chung",
        "intent": "correction / clarification",
        "meaning": "Nguoi dung sua lai thong tin, doi thoi gian, hoac noi Bob hieu sai.",
        "behavior": "Nhan loi gon, cap nhat y dinh theo thong tin moi. Neu lien quan action da tao thi dung agent update/delete can confirm.",
        "tags": "correction,clarify,doi y,khau ngu",
        "phrases": [
            "khong phai cai do",
            "y toi la ngay mai co",
            "nham roi bob",
            "doi lai thanh 5h nha",
            "toi noi hop voi Nam chu khong phai Lan",
            "bo phan do di",
            "lam lai tu dau",
            "sua thanh urgent giup",
            "khong can email chi can checklist",
            "toi muon lich chu khong phai todo",
        ],
    },
    {
        "title": "moc thoi gian doi thuong",
        "intent": "relative time parsing",
        "meaning": "Nguoi dung dung moc thoi gian noi mieng: lat nua, chieu nay, toi mai, dau tuan, cuoi tuan.",
        "behavior": "Dien giai theo thoi diem hien tai. Neu mo ho (mai mot, bua nao) thi hoi lai truoc khi tao action.",
        "tags": "time,relative time,lich,khau ngu",
        "phrases": [
            "lat nua nhac toi",
            "chieu nay lam nhe",
            "toi mai cho vao lich",
            "sang kia gap khach",
            "cuoi tuan nhac don nha",
            "dau tuan sau hop team",
            "tam 3h chieu",
            "khoang 7 8h toi",
            "mai mot tinh tiep",
            "bua nao ranh thi lam",
        ],
    },
    {
        "title": "cau lenh ngan va thieu chu ngu",
        "intent": "ellipsis handling",
        "meaning": "Nguoi dung noi rat ngan, bo chu ngu/vi ngu, Bob phai suy tu context gan nhat nhung khong duoc bia.",
        "behavior": "Neu du context thi xu ly; neu thieu doi tuong/thoi gian quan trong thi hoi lai mot cau ngan.",
        "tags": "ellipsis,context,khau ngu",
        "phrases": [
            "them cai nay",
            "xoa no di",
            "doi sang mai",
            "tim lai cai do",
            "rep giup",
            "cho vao lich",
            "bo khoi list",
            "xem cai vua roi",
            "lam nhu tren",
            "ap dung het",
        ],
    },
    {
        "title": "giao tiep than mat va dai tu",
        "intent": "tone and pronouns",
        "meaning": "Nguoi dung co the xung toi/minh/tui/tao/em/anh/chi/bro; day la tone, khong phai du lieu can ghi nho tru khi user yeu cau.",
        "behavior": "Tra loi cung ngon ngu va ton trong, khong bat chuoc tho lo neu khong phu hop. Chi nho xung ho khi user noi ro tu nay.",
        "tags": "tone,pronoun,style,khau ngu",
        "phrases": [
            "bob oi coi gium tui",
            "bro xem cai mail nay",
            "em nho anh lich hop",
            "chi muon doi lich",
            "tao can checklist nhanh",
            "minh hoi chut",
            "ban xem giup minh",
            "nho nha bob",
            "lam nhanh cho toi voi",
            "tu nay goi toi la anh nha",
        ],
    },
    {
        "title": "mo ho can hoi lai",
        "intent": "clarifying question",
        "meaning": "Nguoi dung noi thieu doi tuong, thoi gian, hanh dong, hoac co nhieu cach hieu.",
        "behavior": "Hoi lai dung phan thieu, khong doan bua. Neu hanh dong co rui ro thi khong thuc hien.",
        "tags": "ambiguity,clarify,safety,khau ngu",
        "phrases": [
            "dat cai do giup toi",
            "gui no di",
            "doi lich do nha",
            "xoa het di",
            "lam nhu bua truoc",
            "nhac toi cai viec kia",
            "tim cai mail hom do",
            "chuyen qua ngay khac",
            "rep sao cung duoc",
            "sap xep lai het cho toi",
        ],
    },
    {
        "title": "hanh dong nhay cam can canh bao",
        "intent": "safety and confirmation",
        "meaning": "Nguoi dung yeu cau gui mail, xoa du lieu, doi/xoa lich, ngat ket noi, tac dong ben ngoai.",
        "behavior": "Luon can xac nhan ro truoc khi claim da lam. Neu chua co tool ho tro thi noi khong lam duoc va goi y cach thay the.",
        "tags": "safety,confirmation,external action,khau ngu",
        "phrases": [
            "gui luon mail do",
            "xoa sach lich su",
            "huy het lich hom nay",
            "ngat gmail di",
            "doi tat ca meeting sang mai",
            "xoa may email nay",
            "gui cho khach hang ngay",
            "cap nhat calendar that luon",
            "lam het thay toi",
            "tu dong xu ly may cai nay",
        ],
    },
    {
        "title": "loi noi ve tai lieu va file",
        "intent": "email.search / chat.freeform",
        "meaning": "Nguoi dung hoi file, attachment, tai lieu trong email hoac can tom tat noi dung neu da co context.",
        "behavior": "Tim email/file metadata neu Gmail co. Neu khong co noi dung file thi noi ro chua doc duoc file that.",
        "tags": "file,attachment,email,document,khau ngu",
        "phrases": [
            "tim file bao cao hom bua",
            "ai gui cai pdf do vay",
            "mail nao co attachment",
            "kiem giup file hop dong",
            "co tai lieu nao ve project khong",
            "doc cai file trong mail nay duoc khong",
            "tom tat attachment neu co",
            "tim lai slide thuyet trinh",
            "file bang gia nam o email nao",
            "co link drive nao trong mail khong",
        ],
    },
    {
        "title": "nhieu y trong mot cau",
        "intent": "multi-intent handling",
        "meaning": "Nguoi dung noi nhieu yeu cau cung luc: tim mail, tao lich, them checklist, soan reply.",
        "behavior": "Uu tien y chinh an toan. Neu co nhieu write/action, chia thanh tung buoc va hoi user chon/xac nhan.",
        "tags": "multi intent,workflow,khau ngu",
        "phrases": [
            "tim mail khach roi dat lich follow up",
            "doc email va tao checklist viec can lam",
            "xem lich roi xep ngay giup toi",
            "soan reply va nhac toi gui sau",
            "tim deadline roi cho vao lich",
            "tom tat inbox roi noi viec nao can lam",
            "doi lich hop va bao lai cho team",
            "them task xong goi y khung gio",
            "kiem mail roi draft cau tra loi",
            "xem hom nay co gi roi sap uu tien",
        ],
    },
]


def _build_colloquial_document(index, table):
    lines = [
        f"Bang khau ngu {index:02d}: {table['title']}",
        f"Intent/chuc nang goi y: {table['intent']}",
        f"Cach Bob hieu: {table['meaning']}",
        f"Cach xu ly: {table['behavior']}",
        "Mau cau noi doi thuong:",
    ]
    lines.extend(
        f"{phrase_index}. \"{phrase}\""
        for phrase_index, phrase in enumerate(table["phrases"], start=1)
    )
    lines.append(
        "Nguyen tac: uu tien du lieu workspace that, khong bia, hoi lai khi thieu thong tin, "
        "va khong thuc hien hanh dong rui ro neu chua xac nhan."
    )
    return (
        f"Khau ngu {index:02d}: {table['title']}",
        "\n".join(lines),
        f"khau ngu,spoken language,{table['intent']},{table['tags']}",
    )


COLLOQUIAL_SEED_DOCUMENTS = [
    _build_colloquial_document(index, table)
    for index, table in enumerate(_COLLOQUIAL_TABLES, start=1)
]

COLLOQUIAL_SEED_EXAMPLE_COUNT = sum(len(table["phrases"]) for table in _COLLOQUIAL_TABLES)
