import * as SecureStore from 'expo-secure-store';
import { getMobileUserId } from '../api/session';

const ACTIVE_CHAT_SESSION_KEY = 'flowmate.activeChatSession';

let pendingWrite = Promise.resolve();

function normalizeSessionId(value) {
  return String(value || '').trim();
}

function currentOwner() {
  return getMobileUserId() || 'anonymous';
}

export function getChatSessionOwner() {
  return currentOwner();
}

function sessionMapFromStored(stored) {
  if (!stored) return {};
  try {
    const parsed = JSON.parse(stored);
    if (parsed?.sessions && typeof parsed.sessions === 'object') {
      return { ...parsed.sessions };
    }
    // Backward-compatible read of the original single-owner format.
    if (parsed?.owner && parsed?.sessionId) {
      return { [parsed.owner]: normalizeSessionId(parsed.sessionId) };
    }
  } catch {
    return {};
  }
  return {};
}

export async function loadActiveChatSessionId(expectedOwner = currentOwner()) {
  // A tab switch can remount ChatScreen while the previous instance is still
  // flushing its last session change. Waiting here prevents an older value
  // from being read and adopted again.
  await pendingWrite.catch(() => {});
  if (expectedOwner !== currentOwner()) return '';

  try {
    const stored = await SecureStore.getItemAsync(ACTIVE_CHAT_SESSION_KEY);
    if (expectedOwner !== currentOwner()) return '';
    return normalizeSessionId(sessionMapFromStored(stored)[expectedOwner]);
  } catch {
    // Secure storage can be unavailable on some development targets. Chat can
    // still work with the in-memory session generated by ChatScreen.
    return '';
  }
}

export function persistActiveChatSessionId(value, expectedOwner = currentOwner()) {
  const sessionId = normalizeSessionId(value);
  if (expectedOwner !== currentOwner()) return Promise.resolve(false);

  pendingWrite = pendingWrite
    .catch(() => {})
    .then(async () => {
      if (expectedOwner !== currentOwner()) return false;
      const stored = await SecureStore.getItemAsync(ACTIVE_CHAT_SESSION_KEY);
      if (expectedOwner !== currentOwner()) return false;
      const sessions = sessionMapFromStored(stored);
      if (sessionId) {
        sessions[expectedOwner] = sessionId;
      } else {
        delete sessions[expectedOwner];
      }
      if (!Object.keys(sessions).length) {
        await SecureStore.deleteItemAsync(ACTIVE_CHAT_SESSION_KEY);
        return true;
      }
      await SecureStore.setItemAsync(
        ACTIVE_CHAT_SESSION_KEY,
        JSON.stringify({ version: 2, sessions }),
      );
      return true;
    })
    .catch(() => false);

  return pendingWrite;
}
